name: Semantic Versioning, Docker Build, Push, and Scan

on:
  push:
    branches:
      - main

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read

jobs:
  semver:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.release.outputs.tag_name }}
    permissions:
      contents: 'write'
      id-token: 'write'
      packages: 'write'
      repository-projects: 'write'
      pull-requests: read


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 🔖 Create Release.
        id: release
        uses: rymndhng/release-on-push-action@aebba2bbce07a9474bf95e8710e5ee8a9e922fe2 #v0.28.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: minor
          use_github_release_notes: true


      - name: version ${{ steps.release.outputs.tag_name }}
        run: echo "version=${{ steps.release.outputs.tag_name }}" >> $GITHUB_OUTPUT

  docker:
    needs: semver
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 #v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Find Dockerfiles
        id: find-dockerfiles
        shell: bash
        run: |
          find . -name "*.Dockerfile"
          echo "dockerfiles=$(find . -name "*.Dockerfile")" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ${{ steps.find-dockerfiles.outputs.dockerfiles }}
          push: true
          provenance: mode=max
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ needs.semver.outputs.new_version }}
            ghcr.io/${{ github.repository }}:latest
